plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.gharkaam.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.gharkaam.app"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
implementation 'com.google.firebase:firebase-storage'
    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-auth'
}
